name: Deploy ECS

# on:
#   workflow_run:
#     workflows:
#       - E2E Tests
#     branches:
#       - devops/add-ecs-deploy
#     types:
#       - completed

on:
  push:
    branches:
      - devops/add-ecs-deploy

env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: relayer-0-stage
  ENVIRONMENT: STAGE

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - run: sleep 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::852551629426:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }}

      - name: Deploy to Amazon ECS - Relayer 0
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-0_${{ env.ENVIRONMENT }}.json
          service: relayer-0-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true

      - name: Deploy to Amazon ECS - Relayer 1
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-1_${{ env.ENVIRONMENT }}.json
          service: relayer-1-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true

      - name: Deploy to Amazon ECS - Relayer 2
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-2_${{ env.ENVIRONMENT }}.json
          service: relayer-2-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true

      - name: Deploy to Amazon ECS - Relayer 3
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-3_${{ env.ENVIRONMENT }}.json
          service: relayer-3-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true

      - name: Deploy to Amazon ECS - Relayer 4
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-4_${{ env.ENVIRONMENT }}.json
          service: relayer-4-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true
